language: python

os:
  - osx
  - linux

python:
  - "2.7"

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python  ; fi

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - py.test
